version: '3.4'

services:
  apiserver:
    image: vds_api
    container_name: vds_api
    ports:
      - "52719:80"
      - "22222:22"
    build:
      context: .
      dockerfile: vds_api/Dockerfile
  authserver:
    image: vds_auth
    container_name: vds_auth
    ports:
      - "51927:80"
      - "22223:22"
    build:
      context: .
      dockerfile: vds_auth/Dockerfile